name: Backend CI

on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - dev
      - main

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version to') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests=false

      - name: Run tests
        run: ./mvnw test

  version-bump:
    needs: tests
    if: github.ref_name == 'main' && !contains(github.event.head_commit.message, 'Bump version to')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Bump version if not manually changed (main only)
        run: |
          CURRENT_VERSION=$(./mvnw help:evaluate -DforceStdout -q -Dexpression=project.version)
          PREV_VERSION=$(git show HEAD~1:pom.xml | grep '<version>' | head -1 | sed -E 's./<version>([^<]+)<.*/\1/')
          if [ "$CURRENT_VERSION" = "$PREV_VERSION" ]; then
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
            mvn versions:set -DnewVersion="$NEW_VERSION"
            mvn versions:commit
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add pom.xml
            git commit -m "Bump version to $NEW_VERSION"
            git push
          else
            echo "Version was manually changed ($PREV_VERSION -> $CURRENT_VERSION), skipping auto-increment"
          fi
