name: Backend CI

on:
  pull_request:
    paths:
      - '**'
  push:
    branches:
      - dev
      - main

jobs:
  tests:
    if: ${{ !contains(github.event.head_commit.message, 'Bump version to') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests=true

      - name: Run tests
        run: ./mvnw test

