name: Push to Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml
    with:
      skip-if-version-bump: true  # Skip tests on version bump commits

  build-docker:
    needs: run-tests
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      branch: dev
