name: Build Docker on Dev

on:
  push:
    branches:
      - dev
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/*.md'
      - '**/.gitkeep'
      - '**/LICENSE'
      - '**/target/**'
      - '**/.idea/**'
      - '**/*.iml'

permissions:
  contents: read
  packages: write

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml
    
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      build-common: ${{ steps.check-files.outputs.build-common }}
      build-validator: ${{ steps.check-files.outputs.build-validator }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Need previous commit for comparison
      
      - name: Check for file changes
        id: check-files
        run: |
          # Get list of changed files
          echo "Checking for changed files..."
          git diff --name-only HEAD^ HEAD > changed_files.txt
          cat changed_files.txt
          
          # Define files to ignore (blacklist)
          IGNORE_FILES=('README.md' '*.md' '.gitignore' '.gitkeep' 'LICENSE' '*.iml')
          
          # Create a temporary file with all changes
          cp changed_files.txt relevant_changes.txt
          
          # Filter out ignored files
          for pattern in "${IGNORE_FILES[@]}"; do
            grep -v "$pattern" relevant_changes.txt > temp && mv temp relevant_changes.txt || true
          done
          
          # If no relevant files changed, skip builds
          if [ ! -s relevant_changes.txt ]; then
            echo "No relevant files changed, skipping builds"
            echo "build-common=false" >> $GITHUB_OUTPUT
            echo "build-validator=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for module changes
          if grep -q '^ismd-backend-common/' relevant_changes.txt; then
            echo "Common module files changed"
            echo "build-common=true" >> $GITHUB_OUTPUT
          else
            echo "No common module changes"
            echo "build-common=false" >> $GITHUB_OUTPUT
          fi
          
          if grep -q '^ismd-backend-validator/' relevant_changes.txt; then
            echo "Validator module files changed"
            echo "build-validator=true" >> $GITHUB_OUTPUT
          else
            echo "No validator module changes"
            echo "build-validator=false" >> $GITHUB_OUTPUT
          fi

  # Build common module if changed
  build-common:
    needs: [run-tests, check-changes]
    if: needs.check-changes.outputs.build-common == 'true'
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      branch: dev
      module: common

  # Build validator module if changed
  build-validator:
    needs: [run-tests, check-changes]
    if: needs.check-changes.outputs.build-validator == 'true'
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      branch: dev
      module: validator
