name: Build Docker on Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  # Build Docker image for main branch
  build-docker:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      branch: main
      
  # Sync dev with main after Docker build
  sync-dev:
    needs: build-docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          token: ${{ github.token }}
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Merge main into dev
        run: |
          # Get the current main and dev branches
          git fetch origin main dev
          
          # Check out dev branch
          git checkout dev
          
          # Merge main into dev
          echo "Merging main into dev..."
          git merge origin/main -m "Sync dev with main after release [skip ci]"
          
          # Push the changes
          git push origin dev
