name: Push to Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/reusable-test.yml
    with:
      skip-if-version-bump: true  # Skip tests on version bump commits

  bump-version:
    # Skip version bump if commit message already starts with v (e.g., v1.2.3)
    if: ${{ !startsWith(github.event.head_commit.message, 'v') }}
    uses: ./.github/workflows/reusable-version-bump.yml

  # This job runs only when the version changes (auto or manual)
  build-docker:
    needs: [run-tests, bump-version]
    # Only run if the commit message starts with v followed by a number (e.g., v1.2.3)
    # This happens after auto-version bump or manual version change
    if: |
      startsWith(github.event.head_commit.message, 'v') && contains(github.event.head_commit.message, '.')
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      branch: main

  sync-dev:
    needs: build-docker
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR from main to dev
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync dev with main after version bump"
          branch: auto/sync-main-to-dev
          base: dev
          title: "Sync dev with main after version bump"
          body: |
            Automated PR to sync dev with main after version bump.
            This will auto-merge if there are no conflicts.
          delete-branch: true
          draft: false
          labels: automated-pr, sync

      - name: Auto-merge PR if possible
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: automated-pr,sync
          MERGE_METHOD: squash
