name: Reusable Version Bump Workflow

on:
  workflow_call:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for version history

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Bump version if not manually changed
        run: |
          CURRENT_VERSION=$(./mvnw help:evaluate -DforceStdout -q -Dexpression=project.version)
          if git rev-parse HEAD~1 >/dev/null 2>&1; then
            PREV_VERSION=$(git show HEAD~1:pom.xml | grep '<version>' | head -1 | sed -E 's/.*<version>([^<]+)<.*/\1/')
          else
            PREV_VERSION=""
          fi
          # If there's no previous version, or if the version wasn't changed, bump it
          if [ -z "$PREV_VERSION" ] || [ "$CURRENT_VERSION" = "$PREV_VERSION" ]; then
            NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. '{$NF++;print}')
            mvn versions:set -DnewVersion="$NEW_VERSION"
            mvn versions:commit
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add pom.xml
            git commit -m "Bump version to $NEW_VERSION"
            git push
          else
            echo "Version was manually changed ($PREV_VERSION -> $CURRENT_VERSION), skipping auto-increment"
          fi
