name: Reusable Test Workflow

on:
  workflow_call:
    inputs:
      skip-if-version-bump:
        description: 'Skip tests if commit message contains version bump'
        type: boolean
        default: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check for version bump
        id: check-version-bump
        if: inputs.skip-if-version-bump
        run: |
          # Check if commit message starts with 'v' followed by a number (e.g., v1.2.3)
          if [[ "${{ github.event.head_commit.message }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "is_version_bump=true" >> $GITHUB_OUTPUT
          else
            echo "is_version_bump=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout
        if: inputs.skip-if-version-bump == false || steps.check-version-bump.outputs.is_version_bump != 'true'
        uses: actions/checkout@v4

      - name: Set up JDK 17
        if: inputs.skip-if-version-bump == false || steps.check-version-bump.outputs.is_version_bump != 'true'
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Cache Maven packages
        if: inputs.skip-if-version-bump == false || steps.check-version-bump.outputs.is_version_bump != 'true'
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        if: inputs.skip-if-version-bump == false || steps.check-version-bump.outputs.is_version_bump != 'true'
        run: ./mvnw clean package -DskipTests=true

      - name: Run tests
        if: inputs.skip-if-version-bump == false || steps.check-version-bump.outputs.is_version_bump != 'true'
        run: ./mvnw test
